on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  push:
name: continuous-integration
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -covermode=atomic -coverprofile=profile.cov -race ./...
    - name: Lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.21.0
        make lint
    - name: Check formatting
      run: |
        GO111MODULE=off go get -u mvdan.cc/gofumpt/gofumports
        make format
        git diff --exit-code
    - name: Check generate
      run: |
        GO111MODULE=off go get -u github.com/gobuffalo/packr/v2/packr2
        make generate
        git diff --exit-code
    - name: Check completions
      run: |
        make completions
        git diff --exit-code
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
  macOS:
    runs-on: macos-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
  Windows:
    runs-on: windows-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
